# coding: utf-8

"""
    NASCAR.Data.API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class CreateSubscription(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'company_id': 'int',
        'company_type_id': 'int',
        'source_id': 'str',
        'datapoint_id': 'str',
        'topic_id': 'int',
        'is_active': 'bool'
    }

    attribute_map = {
        'company_id': 'company_id',
        'company_type_id': 'company_type_id',
        'source_id': 'source_id',
        'datapoint_id': 'datapoint_id',
        'topic_id': 'topic_id',
        'is_active': 'is_active'
    }

    def __init__(self, company_id=None, company_type_id=None, source_id=None, datapoint_id=None, topic_id=None, is_active=None):  # noqa: E501
        """CreateSubscription - a model defined in Swagger"""  # noqa: E501
        self._company_id = None
        self._company_type_id = None
        self._source_id = None
        self._datapoint_id = None
        self._topic_id = None
        self._is_active = None
        self.discriminator = None
        if company_id is not None:
            self.company_id = company_id
        if company_type_id is not None:
            self.company_type_id = company_type_id
        if source_id is not None:
            self.source_id = source_id
        if datapoint_id is not None:
            self.datapoint_id = datapoint_id
        if topic_id is not None:
            self.topic_id = topic_id
        if is_active is not None:
            self.is_active = is_active

    @property
    def company_id(self):
        """Gets the company_id of this CreateSubscription.  # noqa: E501


        :return: The company_id of this CreateSubscription.  # noqa: E501
        :rtype: int
        """
        return self._company_id

    @company_id.setter
    def company_id(self, company_id):
        """Sets the company_id of this CreateSubscription.


        :param company_id: The company_id of this CreateSubscription.  # noqa: E501
        :type: int
        """

        self._company_id = company_id

    @property
    def company_type_id(self):
        """Gets the company_type_id of this CreateSubscription.  # noqa: E501


        :return: The company_type_id of this CreateSubscription.  # noqa: E501
        :rtype: int
        """
        return self._company_type_id

    @company_type_id.setter
    def company_type_id(self, company_type_id):
        """Sets the company_type_id of this CreateSubscription.


        :param company_type_id: The company_type_id of this CreateSubscription.  # noqa: E501
        :type: int
        """

        self._company_type_id = company_type_id

    @property
    def source_id(self):
        """Gets the source_id of this CreateSubscription.  # noqa: E501


        :return: The source_id of this CreateSubscription.  # noqa: E501
        :rtype: str
        """
        return self._source_id

    @source_id.setter
    def source_id(self, source_id):
        """Sets the source_id of this CreateSubscription.


        :param source_id: The source_id of this CreateSubscription.  # noqa: E501
        :type: str
        """

        self._source_id = source_id

    @property
    def datapoint_id(self):
        """Gets the datapoint_id of this CreateSubscription.  # noqa: E501


        :return: The datapoint_id of this CreateSubscription.  # noqa: E501
        :rtype: str
        """
        return self._datapoint_id

    @datapoint_id.setter
    def datapoint_id(self, datapoint_id):
        """Sets the datapoint_id of this CreateSubscription.


        :param datapoint_id: The datapoint_id of this CreateSubscription.  # noqa: E501
        :type: str
        """

        self._datapoint_id = datapoint_id

    @property
    def topic_id(self):
        """Gets the topic_id of this CreateSubscription.  # noqa: E501


        :return: The topic_id of this CreateSubscription.  # noqa: E501
        :rtype: int
        """
        return self._topic_id

    @topic_id.setter
    def topic_id(self, topic_id):
        """Sets the topic_id of this CreateSubscription.


        :param topic_id: The topic_id of this CreateSubscription.  # noqa: E501
        :type: int
        """

        self._topic_id = topic_id

    @property
    def is_active(self):
        """Gets the is_active of this CreateSubscription.  # noqa: E501


        :return: The is_active of this CreateSubscription.  # noqa: E501
        :rtype: bool
        """
        return self._is_active

    @is_active.setter
    def is_active(self, is_active):
        """Sets the is_active of this CreateSubscription.


        :param is_active: The is_active of this CreateSubscription.  # noqa: E501
        :type: bool
        """

        self._is_active = is_active

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateSubscription, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateSubscription):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
