# coding: utf-8

"""
    NASCAR.Data.API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class EditorRun(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'publish_state': 'PublishState',
        'id': 'int',
        'tracking_id': 'str',
        'in_data_warehouse': 'bool',
        'manually_set': 'bool',
        'last_update': 'datetime',
        'last_updated_by': 'str',
        'nascar_one_race_id': 'int',
        'timing_event_id': 'int',
        'timing_run_id': 'int',
        'name': 'str',
        'timing_finish_at_lap': 'int',
        'timing_run_duration': 'int',
        'timing_run_type': 'int',
        'timing_run_state': 'int',
        'timing_start_time': 'datetime'
    }

    attribute_map = {
        'publish_state': 'PublishState',
        'id': 'id',
        'tracking_id': 'tracking_id',
        'in_data_warehouse': 'InDataWarehouse',
        'manually_set': 'Manually_Set',
        'last_update': 'LastUpdate',
        'last_updated_by': 'LastUpdatedBy',
        'nascar_one_race_id': 'NascarOne_RaceId',
        'timing_event_id': 'Timing_EventId',
        'timing_run_id': 'Timing_RunId',
        'name': 'Name',
        'timing_finish_at_lap': 'Timing_FinishAtLap',
        'timing_run_duration': 'Timing_RunDuration',
        'timing_run_type': 'Timing_RunType',
        'timing_run_state': 'Timing_RunState',
        'timing_start_time': 'Timing_StartTime'
    }

    def __init__(self, publish_state=None, id=None, tracking_id=None, in_data_warehouse=None, manually_set=None, last_update=None, last_updated_by=None, nascar_one_race_id=None, timing_event_id=None, timing_run_id=None, name=None, timing_finish_at_lap=None, timing_run_duration=None, timing_run_type=None, timing_run_state=None, timing_start_time=None):  # noqa: E501
        """EditorRun - a model defined in Swagger"""  # noqa: E501
        self._publish_state = None
        self._id = None
        self._tracking_id = None
        self._in_data_warehouse = None
        self._manually_set = None
        self._last_update = None
        self._last_updated_by = None
        self._nascar_one_race_id = None
        self._timing_event_id = None
        self._timing_run_id = None
        self._name = None
        self._timing_finish_at_lap = None
        self._timing_run_duration = None
        self._timing_run_type = None
        self._timing_run_state = None
        self._timing_start_time = None
        self.discriminator = None
        if publish_state is not None:
            self.publish_state = publish_state
        if id is not None:
            self.id = id
        if tracking_id is not None:
            self.tracking_id = tracking_id
        if in_data_warehouse is not None:
            self.in_data_warehouse = in_data_warehouse
        if manually_set is not None:
            self.manually_set = manually_set
        if last_update is not None:
            self.last_update = last_update
        if last_updated_by is not None:
            self.last_updated_by = last_updated_by
        if nascar_one_race_id is not None:
            self.nascar_one_race_id = nascar_one_race_id
        if timing_event_id is not None:
            self.timing_event_id = timing_event_id
        if timing_run_id is not None:
            self.timing_run_id = timing_run_id
        if name is not None:
            self.name = name
        if timing_finish_at_lap is not None:
            self.timing_finish_at_lap = timing_finish_at_lap
        if timing_run_duration is not None:
            self.timing_run_duration = timing_run_duration
        if timing_run_type is not None:
            self.timing_run_type = timing_run_type
        if timing_run_state is not None:
            self.timing_run_state = timing_run_state
        if timing_start_time is not None:
            self.timing_start_time = timing_start_time

    @property
    def publish_state(self):
        """Gets the publish_state of this EditorRun.  # noqa: E501


        :return: The publish_state of this EditorRun.  # noqa: E501
        :rtype: PublishState
        """
        return self._publish_state

    @publish_state.setter
    def publish_state(self, publish_state):
        """Sets the publish_state of this EditorRun.


        :param publish_state: The publish_state of this EditorRun.  # noqa: E501
        :type: PublishState
        """

        self._publish_state = publish_state

    @property
    def id(self):
        """Gets the id of this EditorRun.  # noqa: E501


        :return: The id of this EditorRun.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this EditorRun.


        :param id: The id of this EditorRun.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def tracking_id(self):
        """Gets the tracking_id of this EditorRun.  # noqa: E501


        :return: The tracking_id of this EditorRun.  # noqa: E501
        :rtype: str
        """
        return self._tracking_id

    @tracking_id.setter
    def tracking_id(self, tracking_id):
        """Sets the tracking_id of this EditorRun.


        :param tracking_id: The tracking_id of this EditorRun.  # noqa: E501
        :type: str
        """

        self._tracking_id = tracking_id

    @property
    def in_data_warehouse(self):
        """Gets the in_data_warehouse of this EditorRun.  # noqa: E501


        :return: The in_data_warehouse of this EditorRun.  # noqa: E501
        :rtype: bool
        """
        return self._in_data_warehouse

    @in_data_warehouse.setter
    def in_data_warehouse(self, in_data_warehouse):
        """Sets the in_data_warehouse of this EditorRun.


        :param in_data_warehouse: The in_data_warehouse of this EditorRun.  # noqa: E501
        :type: bool
        """

        self._in_data_warehouse = in_data_warehouse

    @property
    def manually_set(self):
        """Gets the manually_set of this EditorRun.  # noqa: E501


        :return: The manually_set of this EditorRun.  # noqa: E501
        :rtype: bool
        """
        return self._manually_set

    @manually_set.setter
    def manually_set(self, manually_set):
        """Sets the manually_set of this EditorRun.


        :param manually_set: The manually_set of this EditorRun.  # noqa: E501
        :type: bool
        """

        self._manually_set = manually_set

    @property
    def last_update(self):
        """Gets the last_update of this EditorRun.  # noqa: E501


        :return: The last_update of this EditorRun.  # noqa: E501
        :rtype: datetime
        """
        return self._last_update

    @last_update.setter
    def last_update(self, last_update):
        """Sets the last_update of this EditorRun.


        :param last_update: The last_update of this EditorRun.  # noqa: E501
        :type: datetime
        """

        self._last_update = last_update

    @property
    def last_updated_by(self):
        """Gets the last_updated_by of this EditorRun.  # noqa: E501


        :return: The last_updated_by of this EditorRun.  # noqa: E501
        :rtype: str
        """
        return self._last_updated_by

    @last_updated_by.setter
    def last_updated_by(self, last_updated_by):
        """Sets the last_updated_by of this EditorRun.


        :param last_updated_by: The last_updated_by of this EditorRun.  # noqa: E501
        :type: str
        """

        self._last_updated_by = last_updated_by

    @property
    def nascar_one_race_id(self):
        """Gets the nascar_one_race_id of this EditorRun.  # noqa: E501


        :return: The nascar_one_race_id of this EditorRun.  # noqa: E501
        :rtype: int
        """
        return self._nascar_one_race_id

    @nascar_one_race_id.setter
    def nascar_one_race_id(self, nascar_one_race_id):
        """Sets the nascar_one_race_id of this EditorRun.


        :param nascar_one_race_id: The nascar_one_race_id of this EditorRun.  # noqa: E501
        :type: int
        """

        self._nascar_one_race_id = nascar_one_race_id

    @property
    def timing_event_id(self):
        """Gets the timing_event_id of this EditorRun.  # noqa: E501


        :return: The timing_event_id of this EditorRun.  # noqa: E501
        :rtype: int
        """
        return self._timing_event_id

    @timing_event_id.setter
    def timing_event_id(self, timing_event_id):
        """Sets the timing_event_id of this EditorRun.


        :param timing_event_id: The timing_event_id of this EditorRun.  # noqa: E501
        :type: int
        """

        self._timing_event_id = timing_event_id

    @property
    def timing_run_id(self):
        """Gets the timing_run_id of this EditorRun.  # noqa: E501


        :return: The timing_run_id of this EditorRun.  # noqa: E501
        :rtype: int
        """
        return self._timing_run_id

    @timing_run_id.setter
    def timing_run_id(self, timing_run_id):
        """Sets the timing_run_id of this EditorRun.


        :param timing_run_id: The timing_run_id of this EditorRun.  # noqa: E501
        :type: int
        """

        self._timing_run_id = timing_run_id

    @property
    def name(self):
        """Gets the name of this EditorRun.  # noqa: E501


        :return: The name of this EditorRun.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this EditorRun.


        :param name: The name of this EditorRun.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def timing_finish_at_lap(self):
        """Gets the timing_finish_at_lap of this EditorRun.  # noqa: E501


        :return: The timing_finish_at_lap of this EditorRun.  # noqa: E501
        :rtype: int
        """
        return self._timing_finish_at_lap

    @timing_finish_at_lap.setter
    def timing_finish_at_lap(self, timing_finish_at_lap):
        """Sets the timing_finish_at_lap of this EditorRun.


        :param timing_finish_at_lap: The timing_finish_at_lap of this EditorRun.  # noqa: E501
        :type: int
        """

        self._timing_finish_at_lap = timing_finish_at_lap

    @property
    def timing_run_duration(self):
        """Gets the timing_run_duration of this EditorRun.  # noqa: E501


        :return: The timing_run_duration of this EditorRun.  # noqa: E501
        :rtype: int
        """
        return self._timing_run_duration

    @timing_run_duration.setter
    def timing_run_duration(self, timing_run_duration):
        """Sets the timing_run_duration of this EditorRun.


        :param timing_run_duration: The timing_run_duration of this EditorRun.  # noqa: E501
        :type: int
        """

        self._timing_run_duration = timing_run_duration

    @property
    def timing_run_type(self):
        """Gets the timing_run_type of this EditorRun.  # noqa: E501


        :return: The timing_run_type of this EditorRun.  # noqa: E501
        :rtype: int
        """
        return self._timing_run_type

    @timing_run_type.setter
    def timing_run_type(self, timing_run_type):
        """Sets the timing_run_type of this EditorRun.


        :param timing_run_type: The timing_run_type of this EditorRun.  # noqa: E501
        :type: int
        """

        self._timing_run_type = timing_run_type

    @property
    def timing_run_state(self):
        """Gets the timing_run_state of this EditorRun.  # noqa: E501


        :return: The timing_run_state of this EditorRun.  # noqa: E501
        :rtype: int
        """
        return self._timing_run_state

    @timing_run_state.setter
    def timing_run_state(self, timing_run_state):
        """Sets the timing_run_state of this EditorRun.


        :param timing_run_state: The timing_run_state of this EditorRun.  # noqa: E501
        :type: int
        """

        self._timing_run_state = timing_run_state

    @property
    def timing_start_time(self):
        """Gets the timing_start_time of this EditorRun.  # noqa: E501


        :return: The timing_start_time of this EditorRun.  # noqa: E501
        :rtype: datetime
        """
        return self._timing_start_time

    @timing_start_time.setter
    def timing_start_time(self, timing_start_time):
        """Sets the timing_start_time of this EditorRun.


        :param timing_start_time: The timing_start_time of this EditorRun.  # noqa: E501
        :type: datetime
        """

        self._timing_start_time = timing_start_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EditorRun, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EditorRun):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
