# coding: utf-8

"""
    NASCAR.Data.API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ERDPSource(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'source_id': 'str',
        'description': 'str',
        'is_active': 'bool',
        'vehicle': 'ERDPSourceVehicle'
    }

    attribute_map = {
        'id': 'id',
        'source_id': 'source_id',
        'description': 'description',
        'is_active': 'is_active',
        'vehicle': 'vehicle'
    }

    def __init__(self, id=None, source_id=None, description=None, is_active=None, vehicle=None):  # noqa: E501
        """ERDPSource - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._source_id = None
        self._description = None
        self._is_active = None
        self._vehicle = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if source_id is not None:
            self.source_id = source_id
        if description is not None:
            self.description = description
        if is_active is not None:
            self.is_active = is_active
        if vehicle is not None:
            self.vehicle = vehicle

    @property
    def id(self):
        """Gets the id of this ERDPSource.  # noqa: E501


        :return: The id of this ERDPSource.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ERDPSource.


        :param id: The id of this ERDPSource.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def source_id(self):
        """Gets the source_id of this ERDPSource.  # noqa: E501


        :return: The source_id of this ERDPSource.  # noqa: E501
        :rtype: str
        """
        return self._source_id

    @source_id.setter
    def source_id(self, source_id):
        """Sets the source_id of this ERDPSource.


        :param source_id: The source_id of this ERDPSource.  # noqa: E501
        :type: str
        """

        self._source_id = source_id

    @property
    def description(self):
        """Gets the description of this ERDPSource.  # noqa: E501


        :return: The description of this ERDPSource.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ERDPSource.


        :param description: The description of this ERDPSource.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def is_active(self):
        """Gets the is_active of this ERDPSource.  # noqa: E501


        :return: The is_active of this ERDPSource.  # noqa: E501
        :rtype: bool
        """
        return self._is_active

    @is_active.setter
    def is_active(self, is_active):
        """Sets the is_active of this ERDPSource.


        :param is_active: The is_active of this ERDPSource.  # noqa: E501
        :type: bool
        """

        self._is_active = is_active

    @property
    def vehicle(self):
        """Gets the vehicle of this ERDPSource.  # noqa: E501


        :return: The vehicle of this ERDPSource.  # noqa: E501
        :rtype: ERDPSourceVehicle
        """
        return self._vehicle

    @vehicle.setter
    def vehicle(self, vehicle):
        """Sets the vehicle of this ERDPSource.


        :param vehicle: The vehicle of this ERDPSource.  # noqa: E501
        :type: ERDPSourceVehicle
        """

        self._vehicle = vehicle

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ERDPSource, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ERDPSource):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
