# coding: utf-8

"""
    NASCAR.Data.API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class LoopStat(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'starting_position': 'int',
        'mid_race_position': 'int',
        'closing_laps_position': 'int',
        'closing_laps_diff': 'int',
        'finishing_position': 'int',
        'best_position': 'int',
        'worst_position': 'int',
        'passing_differential': 'int',
        'green_flag_passes': 'int',
        'green_flag_times_passed': 'int',
        'quality_passes': 'int',
        'average_running_position': 'float',
        'percentage_quality_passes': 'float',
        'fastest_lap': 'int',
        'percentage_fastest_laps': 'float',
        'laps_in_top15': 'int',
        'percentage_laps_in_top15': 'float',
        'laps_led': 'int',
        'percentage_laps_led': 'float',
        'laps_completed': 'int',
        'fastest_on_restarts': 'float',
        'average_speed_early_run': 'float',
        'average_speed_late_run': 'float',
        'average_green_flag_speed': 'float',
        'average_speed_in_traffic': 'float',
        'driver_rating': 'float',
        'racesegment1_mph_difference': 'float',
        'racesegment2_mph_difference': 'float',
        'racesegment3_mph_difference': 'float',
        'racesegment4_mph_difference': 'float',
        'total_mph_difference': 'float',
        'took_lead': 'float',
        'vehicle_number': 'str'
    }

    attribute_map = {
        'starting_position': 'starting_position',
        'mid_race_position': 'mid_race_position',
        'closing_laps_position': 'closing_laps_position',
        'closing_laps_diff': 'closing_laps_diff',
        'finishing_position': 'finishing_position',
        'best_position': 'best_position',
        'worst_position': 'worst_position',
        'passing_differential': 'passing_differential',
        'green_flag_passes': 'green_flag_passes',
        'green_flag_times_passed': 'green_flag_times_passed',
        'quality_passes': 'quality_passes',
        'average_running_position': 'average_running_position',
        'percentage_quality_passes': 'percentage_quality_passes',
        'fastest_lap': 'fastest_lap',
        'percentage_fastest_laps': 'percentage_fastest_laps',
        'laps_in_top15': 'laps_in_top15',
        'percentage_laps_in_top15': 'percentage_laps_in_top15',
        'laps_led': 'laps_led',
        'percentage_laps_led': 'percentage_laps_led',
        'laps_completed': 'laps_completed',
        'fastest_on_restarts': 'fastest_on_restarts',
        'average_speed_early_run': 'average_speed_early_run',
        'average_speed_late_run': 'average_speed_late_run',
        'average_green_flag_speed': 'average_green_flag_speed',
        'average_speed_in_traffic': 'average_speed_in_traffic',
        'driver_rating': 'driver_rating',
        'racesegment1_mph_difference': 'racesegment1_MPH_difference',
        'racesegment2_mph_difference': 'racesegment2_MPH_difference',
        'racesegment3_mph_difference': 'racesegment3_MPH_difference',
        'racesegment4_mph_difference': 'racesegment4_MPH_difference',
        'total_mph_difference': 'total_MPH_difference',
        'took_lead': 'took_lead',
        'vehicle_number': 'vehicle_number'
    }

    def __init__(self, starting_position=None, mid_race_position=None, closing_laps_position=None, closing_laps_diff=None, finishing_position=None, best_position=None, worst_position=None, passing_differential=None, green_flag_passes=None, green_flag_times_passed=None, quality_passes=None, average_running_position=None, percentage_quality_passes=None, fastest_lap=None, percentage_fastest_laps=None, laps_in_top15=None, percentage_laps_in_top15=None, laps_led=None, percentage_laps_led=None, laps_completed=None, fastest_on_restarts=None, average_speed_early_run=None, average_speed_late_run=None, average_green_flag_speed=None, average_speed_in_traffic=None, driver_rating=None, racesegment1_mph_difference=None, racesegment2_mph_difference=None, racesegment3_mph_difference=None, racesegment4_mph_difference=None, total_mph_difference=None, took_lead=None, vehicle_number=None):  # noqa: E501
        """LoopStat - a model defined in Swagger"""  # noqa: E501
        self._starting_position = None
        self._mid_race_position = None
        self._closing_laps_position = None
        self._closing_laps_diff = None
        self._finishing_position = None
        self._best_position = None
        self._worst_position = None
        self._passing_differential = None
        self._green_flag_passes = None
        self._green_flag_times_passed = None
        self._quality_passes = None
        self._average_running_position = None
        self._percentage_quality_passes = None
        self._fastest_lap = None
        self._percentage_fastest_laps = None
        self._laps_in_top15 = None
        self._percentage_laps_in_top15 = None
        self._laps_led = None
        self._percentage_laps_led = None
        self._laps_completed = None
        self._fastest_on_restarts = None
        self._average_speed_early_run = None
        self._average_speed_late_run = None
        self._average_green_flag_speed = None
        self._average_speed_in_traffic = None
        self._driver_rating = None
        self._racesegment1_mph_difference = None
        self._racesegment2_mph_difference = None
        self._racesegment3_mph_difference = None
        self._racesegment4_mph_difference = None
        self._total_mph_difference = None
        self._took_lead = None
        self._vehicle_number = None
        self.discriminator = None
        if starting_position is not None:
            self.starting_position = starting_position
        if mid_race_position is not None:
            self.mid_race_position = mid_race_position
        if closing_laps_position is not None:
            self.closing_laps_position = closing_laps_position
        if closing_laps_diff is not None:
            self.closing_laps_diff = closing_laps_diff
        if finishing_position is not None:
            self.finishing_position = finishing_position
        if best_position is not None:
            self.best_position = best_position
        if worst_position is not None:
            self.worst_position = worst_position
        if passing_differential is not None:
            self.passing_differential = passing_differential
        if green_flag_passes is not None:
            self.green_flag_passes = green_flag_passes
        if green_flag_times_passed is not None:
            self.green_flag_times_passed = green_flag_times_passed
        if quality_passes is not None:
            self.quality_passes = quality_passes
        if average_running_position is not None:
            self.average_running_position = average_running_position
        if percentage_quality_passes is not None:
            self.percentage_quality_passes = percentage_quality_passes
        if fastest_lap is not None:
            self.fastest_lap = fastest_lap
        if percentage_fastest_laps is not None:
            self.percentage_fastest_laps = percentage_fastest_laps
        if laps_in_top15 is not None:
            self.laps_in_top15 = laps_in_top15
        if percentage_laps_in_top15 is not None:
            self.percentage_laps_in_top15 = percentage_laps_in_top15
        if laps_led is not None:
            self.laps_led = laps_led
        if percentage_laps_led is not None:
            self.percentage_laps_led = percentage_laps_led
        if laps_completed is not None:
            self.laps_completed = laps_completed
        if fastest_on_restarts is not None:
            self.fastest_on_restarts = fastest_on_restarts
        if average_speed_early_run is not None:
            self.average_speed_early_run = average_speed_early_run
        if average_speed_late_run is not None:
            self.average_speed_late_run = average_speed_late_run
        if average_green_flag_speed is not None:
            self.average_green_flag_speed = average_green_flag_speed
        if average_speed_in_traffic is not None:
            self.average_speed_in_traffic = average_speed_in_traffic
        if driver_rating is not None:
            self.driver_rating = driver_rating
        if racesegment1_mph_difference is not None:
            self.racesegment1_mph_difference = racesegment1_mph_difference
        if racesegment2_mph_difference is not None:
            self.racesegment2_mph_difference = racesegment2_mph_difference
        if racesegment3_mph_difference is not None:
            self.racesegment3_mph_difference = racesegment3_mph_difference
        if racesegment4_mph_difference is not None:
            self.racesegment4_mph_difference = racesegment4_mph_difference
        if total_mph_difference is not None:
            self.total_mph_difference = total_mph_difference
        if took_lead is not None:
            self.took_lead = took_lead
        if vehicle_number is not None:
            self.vehicle_number = vehicle_number

    @property
    def starting_position(self):
        """Gets the starting_position of this LoopStat.  # noqa: E501


        :return: The starting_position of this LoopStat.  # noqa: E501
        :rtype: int
        """
        return self._starting_position

    @starting_position.setter
    def starting_position(self, starting_position):
        """Sets the starting_position of this LoopStat.


        :param starting_position: The starting_position of this LoopStat.  # noqa: E501
        :type: int
        """

        self._starting_position = starting_position

    @property
    def mid_race_position(self):
        """Gets the mid_race_position of this LoopStat.  # noqa: E501


        :return: The mid_race_position of this LoopStat.  # noqa: E501
        :rtype: int
        """
        return self._mid_race_position

    @mid_race_position.setter
    def mid_race_position(self, mid_race_position):
        """Sets the mid_race_position of this LoopStat.


        :param mid_race_position: The mid_race_position of this LoopStat.  # noqa: E501
        :type: int
        """

        self._mid_race_position = mid_race_position

    @property
    def closing_laps_position(self):
        """Gets the closing_laps_position of this LoopStat.  # noqa: E501


        :return: The closing_laps_position of this LoopStat.  # noqa: E501
        :rtype: int
        """
        return self._closing_laps_position

    @closing_laps_position.setter
    def closing_laps_position(self, closing_laps_position):
        """Sets the closing_laps_position of this LoopStat.


        :param closing_laps_position: The closing_laps_position of this LoopStat.  # noqa: E501
        :type: int
        """

        self._closing_laps_position = closing_laps_position

    @property
    def closing_laps_diff(self):
        """Gets the closing_laps_diff of this LoopStat.  # noqa: E501


        :return: The closing_laps_diff of this LoopStat.  # noqa: E501
        :rtype: int
        """
        return self._closing_laps_diff

    @closing_laps_diff.setter
    def closing_laps_diff(self, closing_laps_diff):
        """Sets the closing_laps_diff of this LoopStat.


        :param closing_laps_diff: The closing_laps_diff of this LoopStat.  # noqa: E501
        :type: int
        """

        self._closing_laps_diff = closing_laps_diff

    @property
    def finishing_position(self):
        """Gets the finishing_position of this LoopStat.  # noqa: E501


        :return: The finishing_position of this LoopStat.  # noqa: E501
        :rtype: int
        """
        return self._finishing_position

    @finishing_position.setter
    def finishing_position(self, finishing_position):
        """Sets the finishing_position of this LoopStat.


        :param finishing_position: The finishing_position of this LoopStat.  # noqa: E501
        :type: int
        """

        self._finishing_position = finishing_position

    @property
    def best_position(self):
        """Gets the best_position of this LoopStat.  # noqa: E501


        :return: The best_position of this LoopStat.  # noqa: E501
        :rtype: int
        """
        return self._best_position

    @best_position.setter
    def best_position(self, best_position):
        """Sets the best_position of this LoopStat.


        :param best_position: The best_position of this LoopStat.  # noqa: E501
        :type: int
        """

        self._best_position = best_position

    @property
    def worst_position(self):
        """Gets the worst_position of this LoopStat.  # noqa: E501


        :return: The worst_position of this LoopStat.  # noqa: E501
        :rtype: int
        """
        return self._worst_position

    @worst_position.setter
    def worst_position(self, worst_position):
        """Sets the worst_position of this LoopStat.


        :param worst_position: The worst_position of this LoopStat.  # noqa: E501
        :type: int
        """

        self._worst_position = worst_position

    @property
    def passing_differential(self):
        """Gets the passing_differential of this LoopStat.  # noqa: E501


        :return: The passing_differential of this LoopStat.  # noqa: E501
        :rtype: int
        """
        return self._passing_differential

    @passing_differential.setter
    def passing_differential(self, passing_differential):
        """Sets the passing_differential of this LoopStat.


        :param passing_differential: The passing_differential of this LoopStat.  # noqa: E501
        :type: int
        """

        self._passing_differential = passing_differential

    @property
    def green_flag_passes(self):
        """Gets the green_flag_passes of this LoopStat.  # noqa: E501


        :return: The green_flag_passes of this LoopStat.  # noqa: E501
        :rtype: int
        """
        return self._green_flag_passes

    @green_flag_passes.setter
    def green_flag_passes(self, green_flag_passes):
        """Sets the green_flag_passes of this LoopStat.


        :param green_flag_passes: The green_flag_passes of this LoopStat.  # noqa: E501
        :type: int
        """

        self._green_flag_passes = green_flag_passes

    @property
    def green_flag_times_passed(self):
        """Gets the green_flag_times_passed of this LoopStat.  # noqa: E501


        :return: The green_flag_times_passed of this LoopStat.  # noqa: E501
        :rtype: int
        """
        return self._green_flag_times_passed

    @green_flag_times_passed.setter
    def green_flag_times_passed(self, green_flag_times_passed):
        """Sets the green_flag_times_passed of this LoopStat.


        :param green_flag_times_passed: The green_flag_times_passed of this LoopStat.  # noqa: E501
        :type: int
        """

        self._green_flag_times_passed = green_flag_times_passed

    @property
    def quality_passes(self):
        """Gets the quality_passes of this LoopStat.  # noqa: E501


        :return: The quality_passes of this LoopStat.  # noqa: E501
        :rtype: int
        """
        return self._quality_passes

    @quality_passes.setter
    def quality_passes(self, quality_passes):
        """Sets the quality_passes of this LoopStat.


        :param quality_passes: The quality_passes of this LoopStat.  # noqa: E501
        :type: int
        """

        self._quality_passes = quality_passes

    @property
    def average_running_position(self):
        """Gets the average_running_position of this LoopStat.  # noqa: E501


        :return: The average_running_position of this LoopStat.  # noqa: E501
        :rtype: float
        """
        return self._average_running_position

    @average_running_position.setter
    def average_running_position(self, average_running_position):
        """Sets the average_running_position of this LoopStat.


        :param average_running_position: The average_running_position of this LoopStat.  # noqa: E501
        :type: float
        """

        self._average_running_position = average_running_position

    @property
    def percentage_quality_passes(self):
        """Gets the percentage_quality_passes of this LoopStat.  # noqa: E501


        :return: The percentage_quality_passes of this LoopStat.  # noqa: E501
        :rtype: float
        """
        return self._percentage_quality_passes

    @percentage_quality_passes.setter
    def percentage_quality_passes(self, percentage_quality_passes):
        """Sets the percentage_quality_passes of this LoopStat.


        :param percentage_quality_passes: The percentage_quality_passes of this LoopStat.  # noqa: E501
        :type: float
        """

        self._percentage_quality_passes = percentage_quality_passes

    @property
    def fastest_lap(self):
        """Gets the fastest_lap of this LoopStat.  # noqa: E501


        :return: The fastest_lap of this LoopStat.  # noqa: E501
        :rtype: int
        """
        return self._fastest_lap

    @fastest_lap.setter
    def fastest_lap(self, fastest_lap):
        """Sets the fastest_lap of this LoopStat.


        :param fastest_lap: The fastest_lap of this LoopStat.  # noqa: E501
        :type: int
        """

        self._fastest_lap = fastest_lap

    @property
    def percentage_fastest_laps(self):
        """Gets the percentage_fastest_laps of this LoopStat.  # noqa: E501


        :return: The percentage_fastest_laps of this LoopStat.  # noqa: E501
        :rtype: float
        """
        return self._percentage_fastest_laps

    @percentage_fastest_laps.setter
    def percentage_fastest_laps(self, percentage_fastest_laps):
        """Sets the percentage_fastest_laps of this LoopStat.


        :param percentage_fastest_laps: The percentage_fastest_laps of this LoopStat.  # noqa: E501
        :type: float
        """

        self._percentage_fastest_laps = percentage_fastest_laps

    @property
    def laps_in_top15(self):
        """Gets the laps_in_top15 of this LoopStat.  # noqa: E501


        :return: The laps_in_top15 of this LoopStat.  # noqa: E501
        :rtype: int
        """
        return self._laps_in_top15

    @laps_in_top15.setter
    def laps_in_top15(self, laps_in_top15):
        """Sets the laps_in_top15 of this LoopStat.


        :param laps_in_top15: The laps_in_top15 of this LoopStat.  # noqa: E501
        :type: int
        """

        self._laps_in_top15 = laps_in_top15

    @property
    def percentage_laps_in_top15(self):
        """Gets the percentage_laps_in_top15 of this LoopStat.  # noqa: E501


        :return: The percentage_laps_in_top15 of this LoopStat.  # noqa: E501
        :rtype: float
        """
        return self._percentage_laps_in_top15

    @percentage_laps_in_top15.setter
    def percentage_laps_in_top15(self, percentage_laps_in_top15):
        """Sets the percentage_laps_in_top15 of this LoopStat.


        :param percentage_laps_in_top15: The percentage_laps_in_top15 of this LoopStat.  # noqa: E501
        :type: float
        """

        self._percentage_laps_in_top15 = percentage_laps_in_top15

    @property
    def laps_led(self):
        """Gets the laps_led of this LoopStat.  # noqa: E501


        :return: The laps_led of this LoopStat.  # noqa: E501
        :rtype: int
        """
        return self._laps_led

    @laps_led.setter
    def laps_led(self, laps_led):
        """Sets the laps_led of this LoopStat.


        :param laps_led: The laps_led of this LoopStat.  # noqa: E501
        :type: int
        """

        self._laps_led = laps_led

    @property
    def percentage_laps_led(self):
        """Gets the percentage_laps_led of this LoopStat.  # noqa: E501


        :return: The percentage_laps_led of this LoopStat.  # noqa: E501
        :rtype: float
        """
        return self._percentage_laps_led

    @percentage_laps_led.setter
    def percentage_laps_led(self, percentage_laps_led):
        """Sets the percentage_laps_led of this LoopStat.


        :param percentage_laps_led: The percentage_laps_led of this LoopStat.  # noqa: E501
        :type: float
        """

        self._percentage_laps_led = percentage_laps_led

    @property
    def laps_completed(self):
        """Gets the laps_completed of this LoopStat.  # noqa: E501


        :return: The laps_completed of this LoopStat.  # noqa: E501
        :rtype: int
        """
        return self._laps_completed

    @laps_completed.setter
    def laps_completed(self, laps_completed):
        """Sets the laps_completed of this LoopStat.


        :param laps_completed: The laps_completed of this LoopStat.  # noqa: E501
        :type: int
        """

        self._laps_completed = laps_completed

    @property
    def fastest_on_restarts(self):
        """Gets the fastest_on_restarts of this LoopStat.  # noqa: E501


        :return: The fastest_on_restarts of this LoopStat.  # noqa: E501
        :rtype: float
        """
        return self._fastest_on_restarts

    @fastest_on_restarts.setter
    def fastest_on_restarts(self, fastest_on_restarts):
        """Sets the fastest_on_restarts of this LoopStat.


        :param fastest_on_restarts: The fastest_on_restarts of this LoopStat.  # noqa: E501
        :type: float
        """

        self._fastest_on_restarts = fastest_on_restarts

    @property
    def average_speed_early_run(self):
        """Gets the average_speed_early_run of this LoopStat.  # noqa: E501


        :return: The average_speed_early_run of this LoopStat.  # noqa: E501
        :rtype: float
        """
        return self._average_speed_early_run

    @average_speed_early_run.setter
    def average_speed_early_run(self, average_speed_early_run):
        """Sets the average_speed_early_run of this LoopStat.


        :param average_speed_early_run: The average_speed_early_run of this LoopStat.  # noqa: E501
        :type: float
        """

        self._average_speed_early_run = average_speed_early_run

    @property
    def average_speed_late_run(self):
        """Gets the average_speed_late_run of this LoopStat.  # noqa: E501


        :return: The average_speed_late_run of this LoopStat.  # noqa: E501
        :rtype: float
        """
        return self._average_speed_late_run

    @average_speed_late_run.setter
    def average_speed_late_run(self, average_speed_late_run):
        """Sets the average_speed_late_run of this LoopStat.


        :param average_speed_late_run: The average_speed_late_run of this LoopStat.  # noqa: E501
        :type: float
        """

        self._average_speed_late_run = average_speed_late_run

    @property
    def average_green_flag_speed(self):
        """Gets the average_green_flag_speed of this LoopStat.  # noqa: E501


        :return: The average_green_flag_speed of this LoopStat.  # noqa: E501
        :rtype: float
        """
        return self._average_green_flag_speed

    @average_green_flag_speed.setter
    def average_green_flag_speed(self, average_green_flag_speed):
        """Sets the average_green_flag_speed of this LoopStat.


        :param average_green_flag_speed: The average_green_flag_speed of this LoopStat.  # noqa: E501
        :type: float
        """

        self._average_green_flag_speed = average_green_flag_speed

    @property
    def average_speed_in_traffic(self):
        """Gets the average_speed_in_traffic of this LoopStat.  # noqa: E501


        :return: The average_speed_in_traffic of this LoopStat.  # noqa: E501
        :rtype: float
        """
        return self._average_speed_in_traffic

    @average_speed_in_traffic.setter
    def average_speed_in_traffic(self, average_speed_in_traffic):
        """Sets the average_speed_in_traffic of this LoopStat.


        :param average_speed_in_traffic: The average_speed_in_traffic of this LoopStat.  # noqa: E501
        :type: float
        """

        self._average_speed_in_traffic = average_speed_in_traffic

    @property
    def driver_rating(self):
        """Gets the driver_rating of this LoopStat.  # noqa: E501


        :return: The driver_rating of this LoopStat.  # noqa: E501
        :rtype: float
        """
        return self._driver_rating

    @driver_rating.setter
    def driver_rating(self, driver_rating):
        """Sets the driver_rating of this LoopStat.


        :param driver_rating: The driver_rating of this LoopStat.  # noqa: E501
        :type: float
        """

        self._driver_rating = driver_rating

    @property
    def racesegment1_mph_difference(self):
        """Gets the racesegment1_mph_difference of this LoopStat.  # noqa: E501


        :return: The racesegment1_mph_difference of this LoopStat.  # noqa: E501
        :rtype: float
        """
        return self._racesegment1_mph_difference

    @racesegment1_mph_difference.setter
    def racesegment1_mph_difference(self, racesegment1_mph_difference):
        """Sets the racesegment1_mph_difference of this LoopStat.


        :param racesegment1_mph_difference: The racesegment1_mph_difference of this LoopStat.  # noqa: E501
        :type: float
        """

        self._racesegment1_mph_difference = racesegment1_mph_difference

    @property
    def racesegment2_mph_difference(self):
        """Gets the racesegment2_mph_difference of this LoopStat.  # noqa: E501


        :return: The racesegment2_mph_difference of this LoopStat.  # noqa: E501
        :rtype: float
        """
        return self._racesegment2_mph_difference

    @racesegment2_mph_difference.setter
    def racesegment2_mph_difference(self, racesegment2_mph_difference):
        """Sets the racesegment2_mph_difference of this LoopStat.


        :param racesegment2_mph_difference: The racesegment2_mph_difference of this LoopStat.  # noqa: E501
        :type: float
        """

        self._racesegment2_mph_difference = racesegment2_mph_difference

    @property
    def racesegment3_mph_difference(self):
        """Gets the racesegment3_mph_difference of this LoopStat.  # noqa: E501


        :return: The racesegment3_mph_difference of this LoopStat.  # noqa: E501
        :rtype: float
        """
        return self._racesegment3_mph_difference

    @racesegment3_mph_difference.setter
    def racesegment3_mph_difference(self, racesegment3_mph_difference):
        """Sets the racesegment3_mph_difference of this LoopStat.


        :param racesegment3_mph_difference: The racesegment3_mph_difference of this LoopStat.  # noqa: E501
        :type: float
        """

        self._racesegment3_mph_difference = racesegment3_mph_difference

    @property
    def racesegment4_mph_difference(self):
        """Gets the racesegment4_mph_difference of this LoopStat.  # noqa: E501


        :return: The racesegment4_mph_difference of this LoopStat.  # noqa: E501
        :rtype: float
        """
        return self._racesegment4_mph_difference

    @racesegment4_mph_difference.setter
    def racesegment4_mph_difference(self, racesegment4_mph_difference):
        """Sets the racesegment4_mph_difference of this LoopStat.


        :param racesegment4_mph_difference: The racesegment4_mph_difference of this LoopStat.  # noqa: E501
        :type: float
        """

        self._racesegment4_mph_difference = racesegment4_mph_difference

    @property
    def total_mph_difference(self):
        """Gets the total_mph_difference of this LoopStat.  # noqa: E501


        :return: The total_mph_difference of this LoopStat.  # noqa: E501
        :rtype: float
        """
        return self._total_mph_difference

    @total_mph_difference.setter
    def total_mph_difference(self, total_mph_difference):
        """Sets the total_mph_difference of this LoopStat.


        :param total_mph_difference: The total_mph_difference of this LoopStat.  # noqa: E501
        :type: float
        """

        self._total_mph_difference = total_mph_difference

    @property
    def took_lead(self):
        """Gets the took_lead of this LoopStat.  # noqa: E501


        :return: The took_lead of this LoopStat.  # noqa: E501
        :rtype: float
        """
        return self._took_lead

    @took_lead.setter
    def took_lead(self, took_lead):
        """Sets the took_lead of this LoopStat.


        :param took_lead: The took_lead of this LoopStat.  # noqa: E501
        :type: float
        """

        self._took_lead = took_lead

    @property
    def vehicle_number(self):
        """Gets the vehicle_number of this LoopStat.  # noqa: E501


        :return: The vehicle_number of this LoopStat.  # noqa: E501
        :rtype: str
        """
        return self._vehicle_number

    @vehicle_number.setter
    def vehicle_number(self, vehicle_number):
        """Sets the vehicle_number of this LoopStat.


        :param vehicle_number: The vehicle_number of this LoopStat.  # noqa: E501
        :type: str
        """

        self._vehicle_number = vehicle_number

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LoopStat, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LoopStat):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
