# coding: utf-8

"""
    NASCAR.Data.API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class TrackConfiguration(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'track_id': 'int',
        'track_name': 'str',
        'altitude': 'float',
        'northwest_latitude': 'float',
        'northwest_longitude': 'float',
        'southeast_latitude': 'float',
        'southeast_longitude': 'float',
        'heading': 'float',
        'finish_line_rotation': 'float',
        'finish_line_translate_x': 'float',
        'finish_line_translate_y': 'float',
        'pit_finish_line_rotation': 'float',
        'pit_finish_line_translate_x': 'float',
        'pit_finish_line_translate_y': 'float'
    }

    attribute_map = {
        'id': 'id',
        'track_id': 'track_id',
        'track_name': 'track_name',
        'altitude': 'altitude',
        'northwest_latitude': 'northwest_latitude',
        'northwest_longitude': 'northwest_longitude',
        'southeast_latitude': 'southeast_latitude',
        'southeast_longitude': 'southeast_longitude',
        'heading': 'heading',
        'finish_line_rotation': 'finish_line_rotation',
        'finish_line_translate_x': 'finish_line_translate_x',
        'finish_line_translate_y': 'finish_line_translate_y',
        'pit_finish_line_rotation': 'pit_finish_line_rotation',
        'pit_finish_line_translate_x': 'pit_finish_line_translate_x',
        'pit_finish_line_translate_y': 'pit_finish_line_translate_y'
    }

    def __init__(self, id=None, track_id=None, track_name=None, altitude=None, northwest_latitude=None, northwest_longitude=None, southeast_latitude=None, southeast_longitude=None, heading=None, finish_line_rotation=None, finish_line_translate_x=None, finish_line_translate_y=None, pit_finish_line_rotation=None, pit_finish_line_translate_x=None, pit_finish_line_translate_y=None):  # noqa: E501
        """TrackConfiguration - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._track_id = None
        self._track_name = None
        self._altitude = None
        self._northwest_latitude = None
        self._northwest_longitude = None
        self._southeast_latitude = None
        self._southeast_longitude = None
        self._heading = None
        self._finish_line_rotation = None
        self._finish_line_translate_x = None
        self._finish_line_translate_y = None
        self._pit_finish_line_rotation = None
        self._pit_finish_line_translate_x = None
        self._pit_finish_line_translate_y = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if track_id is not None:
            self.track_id = track_id
        if track_name is not None:
            self.track_name = track_name
        if altitude is not None:
            self.altitude = altitude
        if northwest_latitude is not None:
            self.northwest_latitude = northwest_latitude
        if northwest_longitude is not None:
            self.northwest_longitude = northwest_longitude
        if southeast_latitude is not None:
            self.southeast_latitude = southeast_latitude
        if southeast_longitude is not None:
            self.southeast_longitude = southeast_longitude
        if heading is not None:
            self.heading = heading
        if finish_line_rotation is not None:
            self.finish_line_rotation = finish_line_rotation
        if finish_line_translate_x is not None:
            self.finish_line_translate_x = finish_line_translate_x
        if finish_line_translate_y is not None:
            self.finish_line_translate_y = finish_line_translate_y
        if pit_finish_line_rotation is not None:
            self.pit_finish_line_rotation = pit_finish_line_rotation
        if pit_finish_line_translate_x is not None:
            self.pit_finish_line_translate_x = pit_finish_line_translate_x
        if pit_finish_line_translate_y is not None:
            self.pit_finish_line_translate_y = pit_finish_line_translate_y

    @property
    def id(self):
        """Gets the id of this TrackConfiguration.  # noqa: E501

        Gets or sets the unique identifier for the track configuration.  # noqa: E501

        :return: The id of this TrackConfiguration.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TrackConfiguration.

        Gets or sets the unique identifier for the track configuration.  # noqa: E501

        :param id: The id of this TrackConfiguration.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def track_id(self):
        """Gets the track_id of this TrackConfiguration.  # noqa: E501

        Gets or sets the unique identifier for the track.  # noqa: E501

        :return: The track_id of this TrackConfiguration.  # noqa: E501
        :rtype: int
        """
        return self._track_id

    @track_id.setter
    def track_id(self, track_id):
        """Sets the track_id of this TrackConfiguration.

        Gets or sets the unique identifier for the track.  # noqa: E501

        :param track_id: The track_id of this TrackConfiguration.  # noqa: E501
        :type: int
        """

        self._track_id = track_id

    @property
    def track_name(self):
        """Gets the track_name of this TrackConfiguration.  # noqa: E501

        Gets or sets the name of the track.  # noqa: E501

        :return: The track_name of this TrackConfiguration.  # noqa: E501
        :rtype: str
        """
        return self._track_name

    @track_name.setter
    def track_name(self, track_name):
        """Sets the track_name of this TrackConfiguration.

        Gets or sets the name of the track.  # noqa: E501

        :param track_name: The track_name of this TrackConfiguration.  # noqa: E501
        :type: str
        """

        self._track_name = track_name

    @property
    def altitude(self):
        """Gets the altitude of this TrackConfiguration.  # noqa: E501

        Gets or sets the altitude of the track.  # noqa: E501

        :return: The altitude of this TrackConfiguration.  # noqa: E501
        :rtype: float
        """
        return self._altitude

    @altitude.setter
    def altitude(self, altitude):
        """Sets the altitude of this TrackConfiguration.

        Gets or sets the altitude of the track.  # noqa: E501

        :param altitude: The altitude of this TrackConfiguration.  # noqa: E501
        :type: float
        """

        self._altitude = altitude

    @property
    def northwest_latitude(self):
        """Gets the northwest_latitude of this TrackConfiguration.  # noqa: E501

        Gets or sets the northwest latitude of the track boundary.  # noqa: E501

        :return: The northwest_latitude of this TrackConfiguration.  # noqa: E501
        :rtype: float
        """
        return self._northwest_latitude

    @northwest_latitude.setter
    def northwest_latitude(self, northwest_latitude):
        """Sets the northwest_latitude of this TrackConfiguration.

        Gets or sets the northwest latitude of the track boundary.  # noqa: E501

        :param northwest_latitude: The northwest_latitude of this TrackConfiguration.  # noqa: E501
        :type: float
        """

        self._northwest_latitude = northwest_latitude

    @property
    def northwest_longitude(self):
        """Gets the northwest_longitude of this TrackConfiguration.  # noqa: E501

        Gets or sets the northwest longitude of the track boundary.  # noqa: E501

        :return: The northwest_longitude of this TrackConfiguration.  # noqa: E501
        :rtype: float
        """
        return self._northwest_longitude

    @northwest_longitude.setter
    def northwest_longitude(self, northwest_longitude):
        """Sets the northwest_longitude of this TrackConfiguration.

        Gets or sets the northwest longitude of the track boundary.  # noqa: E501

        :param northwest_longitude: The northwest_longitude of this TrackConfiguration.  # noqa: E501
        :type: float
        """

        self._northwest_longitude = northwest_longitude

    @property
    def southeast_latitude(self):
        """Gets the southeast_latitude of this TrackConfiguration.  # noqa: E501

        Gets or sets the southeast latitude of the track boundary.  # noqa: E501

        :return: The southeast_latitude of this TrackConfiguration.  # noqa: E501
        :rtype: float
        """
        return self._southeast_latitude

    @southeast_latitude.setter
    def southeast_latitude(self, southeast_latitude):
        """Sets the southeast_latitude of this TrackConfiguration.

        Gets or sets the southeast latitude of the track boundary.  # noqa: E501

        :param southeast_latitude: The southeast_latitude of this TrackConfiguration.  # noqa: E501
        :type: float
        """

        self._southeast_latitude = southeast_latitude

    @property
    def southeast_longitude(self):
        """Gets the southeast_longitude of this TrackConfiguration.  # noqa: E501

        Gets or sets the southeast longitude of the track boundary.  # noqa: E501

        :return: The southeast_longitude of this TrackConfiguration.  # noqa: E501
        :rtype: float
        """
        return self._southeast_longitude

    @southeast_longitude.setter
    def southeast_longitude(self, southeast_longitude):
        """Sets the southeast_longitude of this TrackConfiguration.

        Gets or sets the southeast longitude of the track boundary.  # noqa: E501

        :param southeast_longitude: The southeast_longitude of this TrackConfiguration.  # noqa: E501
        :type: float
        """

        self._southeast_longitude = southeast_longitude

    @property
    def heading(self):
        """Gets the heading of this TrackConfiguration.  # noqa: E501

        Gets or sets the heading direction of the track.  # noqa: E501

        :return: The heading of this TrackConfiguration.  # noqa: E501
        :rtype: float
        """
        return self._heading

    @heading.setter
    def heading(self, heading):
        """Sets the heading of this TrackConfiguration.

        Gets or sets the heading direction of the track.  # noqa: E501

        :param heading: The heading of this TrackConfiguration.  # noqa: E501
        :type: float
        """

        self._heading = heading

    @property
    def finish_line_rotation(self):
        """Gets the finish_line_rotation of this TrackConfiguration.  # noqa: E501

        Gets or sets the rotation of the finish line.  # noqa: E501

        :return: The finish_line_rotation of this TrackConfiguration.  # noqa: E501
        :rtype: float
        """
        return self._finish_line_rotation

    @finish_line_rotation.setter
    def finish_line_rotation(self, finish_line_rotation):
        """Sets the finish_line_rotation of this TrackConfiguration.

        Gets or sets the rotation of the finish line.  # noqa: E501

        :param finish_line_rotation: The finish_line_rotation of this TrackConfiguration.  # noqa: E501
        :type: float
        """

        self._finish_line_rotation = finish_line_rotation

    @property
    def finish_line_translate_x(self):
        """Gets the finish_line_translate_x of this TrackConfiguration.  # noqa: E501

        Gets or sets the X-axis translation of the finish line.  # noqa: E501

        :return: The finish_line_translate_x of this TrackConfiguration.  # noqa: E501
        :rtype: float
        """
        return self._finish_line_translate_x

    @finish_line_translate_x.setter
    def finish_line_translate_x(self, finish_line_translate_x):
        """Sets the finish_line_translate_x of this TrackConfiguration.

        Gets or sets the X-axis translation of the finish line.  # noqa: E501

        :param finish_line_translate_x: The finish_line_translate_x of this TrackConfiguration.  # noqa: E501
        :type: float
        """

        self._finish_line_translate_x = finish_line_translate_x

    @property
    def finish_line_translate_y(self):
        """Gets the finish_line_translate_y of this TrackConfiguration.  # noqa: E501

        Gets or sets the Y-axis translation of the finish line.  # noqa: E501

        :return: The finish_line_translate_y of this TrackConfiguration.  # noqa: E501
        :rtype: float
        """
        return self._finish_line_translate_y

    @finish_line_translate_y.setter
    def finish_line_translate_y(self, finish_line_translate_y):
        """Sets the finish_line_translate_y of this TrackConfiguration.

        Gets or sets the Y-axis translation of the finish line.  # noqa: E501

        :param finish_line_translate_y: The finish_line_translate_y of this TrackConfiguration.  # noqa: E501
        :type: float
        """

        self._finish_line_translate_y = finish_line_translate_y

    @property
    def pit_finish_line_rotation(self):
        """Gets the pit_finish_line_rotation of this TrackConfiguration.  # noqa: E501

        Gets or sets the rotation of the pit finish line.  # noqa: E501

        :return: The pit_finish_line_rotation of this TrackConfiguration.  # noqa: E501
        :rtype: float
        """
        return self._pit_finish_line_rotation

    @pit_finish_line_rotation.setter
    def pit_finish_line_rotation(self, pit_finish_line_rotation):
        """Sets the pit_finish_line_rotation of this TrackConfiguration.

        Gets or sets the rotation of the pit finish line.  # noqa: E501

        :param pit_finish_line_rotation: The pit_finish_line_rotation of this TrackConfiguration.  # noqa: E501
        :type: float
        """

        self._pit_finish_line_rotation = pit_finish_line_rotation

    @property
    def pit_finish_line_translate_x(self):
        """Gets the pit_finish_line_translate_x of this TrackConfiguration.  # noqa: E501

        Gets or sets the X-axis translation of the pit finish line.  # noqa: E501

        :return: The pit_finish_line_translate_x of this TrackConfiguration.  # noqa: E501
        :rtype: float
        """
        return self._pit_finish_line_translate_x

    @pit_finish_line_translate_x.setter
    def pit_finish_line_translate_x(self, pit_finish_line_translate_x):
        """Sets the pit_finish_line_translate_x of this TrackConfiguration.

        Gets or sets the X-axis translation of the pit finish line.  # noqa: E501

        :param pit_finish_line_translate_x: The pit_finish_line_translate_x of this TrackConfiguration.  # noqa: E501
        :type: float
        """

        self._pit_finish_line_translate_x = pit_finish_line_translate_x

    @property
    def pit_finish_line_translate_y(self):
        """Gets the pit_finish_line_translate_y of this TrackConfiguration.  # noqa: E501

        Gets or sets the Y-axis translation of the pit finish line.  # noqa: E501

        :return: The pit_finish_line_translate_y of this TrackConfiguration.  # noqa: E501
        :rtype: float
        """
        return self._pit_finish_line_translate_y

    @pit_finish_line_translate_y.setter
    def pit_finish_line_translate_y(self, pit_finish_line_translate_y):
        """Sets the pit_finish_line_translate_y of this TrackConfiguration.

        Gets or sets the Y-axis translation of the pit finish line.  # noqa: E501

        :param pit_finish_line_translate_y: The pit_finish_line_translate_y of this TrackConfiguration.  # noqa: E501
        :type: float
        """

        self._pit_finish_line_translate_y = pit_finish_line_translate_y

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TrackConfiguration, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TrackConfiguration):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
